---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-load-tests-workspace
- name: bosh-src
- name: bosh-cli
- name: bosh-agent

run:
  path: bosh-load-tests-workspace/ci/tasks/test.sh

params:
  DB: postgresql
  RUBY_VERSION: 2.3
  LEGACY: false
  BOSH_SRC_PATH: bosh-src/src
  CLI_DIR_PATH: bosh-cli
