---
networks:
- name: default
  subnets:
  - range: "10.245.0.0/16"
    gateway: "10.245.0.1"
    dns: ["8.8.8.8"]
    static:
    - "10.245.0.10-10.245.0.254"
    - "10.245.1.1-10.245.8.254"
    reserved: []
    cloud_properties:
      name: director_network
compilation:
  workers: 1
  network: default
  cloud_properties: {}
vm_types:
- name: default
  cloud_properties: {}
