---
networks:
- name: default
  subnets:         
  - range: "192.168.1.0/24"
    gateway: "192.168.1.1"
    dns: ["192.168.1.1", "192.168.1.2"]
    static: ["192.168.1.10-192.168.1.30"]
    reserved: []
    cloud_properties: {}
compilation:
  workers: 1
  network: default
  cloud_properties: {}
resource_pools:
- name: default
  cloud_properties: {}
  network: default
  stemcell:
    name: 'ubuntu-stemcell'
    version: '1'
