---
name: {{ .DeploymentName }}
director_uuid: {{ .DirectorUUID }}
networks:
- name: default
  subnets:
  - range: "10.245.{{ .DeploymentIndex }}.0/24"
    gateway: "10.245.{{ .DeploymentIndex }}.1"
    dns: ["8.8.8.8"]
    static: [ {{ .StaticIPs }} ]
    reserved: ["10.245.{{ .DeploymentIndex }}.3"]
    cloud_properties:
      name: director_network
compilation:
  workers: 1
  network: default
  cloud_properties: {}
resource_pools:
- name: default
  cloud_properties: {}
  network: default
  stemcell:
    os: ubuntu-trusty
    version: latest
releases:
- name: bosh-release
  version: 0.1-dev
update:
  canaries: 2
  canary_watch_time: 4000
  max_in_flight: 4
  update_watch_time: 20
jobs:
- name: simple
  templates:
  - name: simple
  resource_pool: default
  instances: 5
  networks:
  - name: default
    static_ips: [ {{ .StaticIPs }} ]
  properties: {}
