---
name: {{ .DeploymentName }}
director_uuid: {{ .DirectorUUID }}
networks:
- name: default
  subnets:
  - range: "192.168.1.0/24"
    gateway: "192.168.1.1"
    dns: ["8.8.8.8"]
    static: ["192.168.1.10-192.168.1.30"]
    reserved: []
    cloud_properties: {}
compilation:
  workers: 1
  network: default
  cloud_properties: {}
resource_pools:
- name: default
  cloud_properties: {}
  network: default
  stemcell:
    os: ubuntu-trusty
    version: latest
releases:
- name: bosh-release
  version: 0.1-dev
update:
  canaries: 2
  canary_watch_time: 4000
  max_in_flight: 4
  update_watch_time: 20
jobs:
- name: simple
  templates:
  - name: simple
  resource_pool: default
  instances: 8
  networks:
  - name: default
    static_ips:
    - 192.168.1.10
    - 192.168.1.11
    - 192.168.1.12
    - 192.168.1.13
    - 192.168.1.14
    - 192.168.1.15
    - 192.168.1.16
    - 192.168.1.17
  properties: {}