---
name: {{ .DeploymentName }}
director_uuid: {{ .DirectorUUID }}
releases:
- name: bosh-release
  version: 0.1-dev
update:
  canaries: 2
  canary_watch_time: 1000-3600000
  max_in_flight: 2
  update_watch_time: 1000-3600000
jobs:
- name: simple
  templates:
  - name: simple
  vm_type: default
  stemcell: default
  instances: 10
  networks:
  - name: default
  properties: {}
stemcells:
- alias: default
  name: 'bosh-warden-boshlite-ubuntu-trusty-go_agent'
  version: latest
